name: "Generate Doxygen documentation"
description: "This action generates Doxygen documentation for the project"

runs:
  using: "composite"
  steps:

    - name: Generar documentación
      shell: bash
      run: |
        doxygen Doxyfile
        if [ ! -d "./documentation" ]; then
          echo "Error: Documentation directory was not created."
          exit 1
        fi

    - name: Verify documentation generation
      shell: bash
      run: test -d ./documentation

    - name: Compress documentation
      shell: bash
      run: tar -czvf doxygen_docs.tar.gz ./documentation

    - name: Upload documentation as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Doxygen-Docs
        path: doxygen_docs.tar.gz
